name: Build and Push Product Service

on:
  push:
    branches: [ "main"]

permissions:
  contents: read
  packages: read  # <--- Bắt buộc phải có dòng này

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Danh sách các service bạn muốn build (tên folder và tên image)
        service: [product-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Bước 1: Build file .jar bằng Gradle
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test
        env:
          # Nhớ phải có đoạn này thì permissions ở trên mới có tác dụng
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Bước 2: Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker Image và Đẩy lên (Push)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Đặt tên cứng luôn vì đây là repo riêng của product-service
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest